### ISSUE TITLE
Support Pinterest Rich Pin

### ISSUE THREAD

**Issue by imsus** [dareenzo/seo-fu#2]
Add Pinterest's Rich Pin Support more on here: [https://developers.pinterest.com/docs/rich-pins/overview/](https://developers.pinterest.com/docs/rich-pins/overview/)

**Comment by PauloPhagula** [comment]
Hi @imsus,

thanks again for your suggestion.

I haven't had to add these before, but as per the description on the Pinterest site, all that must be done is including either JSON+LD or open graph tags, and then validating on their console.

In that case I'd consider this to be already done as JSON+LD and open graph tags are already included.

Please, let me know I'm missing something.

Thanks
