### ISSUE TITLE
Duplicate "URL" on JSON+LD

### ISSUE THREAD

**Issue by imsus** [dareenzo/seo-fu#3]
Check it out on line 336 & 338: [https://github.com/dareenzo/seo-fu/blob/8a88bc8bd8295e030433419a277aa09cbe28632c/seo-fu.html#L336-L338](https://github.com/dareenzo/seo-fu/blob/8a88bc8bd8295e030433419a277aa09cbe28632c/seo-fu.html#L336-L338)

**Comment by PauloPhagula** [comment]
Hi @imsus,

thanks for spotting and reporting the issue. I've fixed it on 2e33d3f
